name: Publish Dictionary Files

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Prepare working directories
        run: |
          mkdir -p tmp/input tmp/output

      - name: Prepare source dictionary
        run: |
          cd external/german-morph-dictionaries
          unzip morf_dict.zip -d ../../tmp/input/

      - name: Generate filtered dictionaries
        run: |
          cd src
          python filter_whitelist.py ../tmp/input/DE_morph_dict.txt ../tmp/output/whitelist_dict.txt ../data/whitelists/ADJ_whitelist.txt ../data/whitelists/NN_whitelist.txt
          python filter_sensible.py ../tmp/input/DE_morph_dict.txt ../tmp/output/DE_morph_dict_filtered.txt

      - name: Upload Original Dictionary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./tmp/input/DE_morph_dict.txt
          asset_name: DE_morph_dict.txt
          asset_content_type: text/plain

      - name: Upload Whitelist Filtered Dictionary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./tmp/output/whitelist_dict.txt
          asset_name: whitelist_dict.txt
          asset_content_type: text/plain

      - name: Upload Sensible Filtered Dictionary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./tmp/output/DE_morph_dict_filtered.txt
          asset_name: DE_morph_dict_filtered.txt
          asset_content_type: text/plain
