name: Publish Dictionary Files

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ref: master
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Prepare working directories
        id: prepare-dirs
        run: |
          mkdir -p tmp/input tmp/output
          echo "INPUT_DIR=tmp/input" >> "$GITHUB_OUTPUT"
          echo "OUTPUT_DIR=tmp/output" >> "$GITHUB_OUTPUT"

      - name: Prepare source dictionary
        run: |
          cd external/german-morph-dictionaries
          unzip morf_dict.zip -d ../../${{ steps.prepare-dirs.outputs.INPUT_DIR }}

      - name: Generate filtered dictionaries
        id: generate-files
        run: |
          cd src
          python filter_whitelist.py "../${{ steps.prepare-dirs.outputs.INPUT_DIR }}/DE_morph_dict.txt" "../${{ steps.prepare-dirs.outputs.OUTPUT_DIR }}/whitelist_dict.txt" ../data/whitelists/ADJ_whitelist.txt ../data/whitelists/NN_whitelist.txt
          python filter_sensible.py "../${{ steps.prepare-dirs.outputs.INPUT_DIR }}/DE_morph_dict.txt" "../${{ steps.prepare-dirs.outputs.OUTPUT_DIR }}/DE_morph_dict_filtered.txt"
          echo "ORIG_DICT=${{ steps.prepare-dirs.outputs.INPUT_DIR }}/DE_morph_dict.txt" >> "$GITHUB_OUTPUT"
          echo "WHITELIST_DICT=${{ steps.prepare-dirs.outputs.OUTPUT_DIR }}/whitelist_dict.txt" >> "$GITHUB_OUTPUT"
          echo "FILTERED_DICT=${{ steps.prepare-dirs.outputs.OUTPUT_DIR }}/DE_morph_dict_filtered.txt" >> "$GITHUB_OUTPUT"

      - name: Copy files to data/output
        run: |
          mkdir -p data/output
          cp "${{ steps.generate-files.outputs.ORIG_DICT }}" data/output/DE_morph_dict.txt
          cp "${{ steps.generate-files.outputs.WHITELIST_DICT }}" data/output/whitelist_dict.txt
          cp "${{ steps.generate-files.outputs.FILTERED_DICT }}" data/output/DE_morph_dict_filtered.txt

      - name: Commit updated dictionaries
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/output/whitelist_dict.txt data/output/DE_morph_dict_filtered.txt data/output/DE_morph_dict.txt
          git commit -m "Update dictionary files for release ${{ github.event.release.tag_name }}"
          git push origin master

      - name: Upload Original Dictionary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.generate-files.outputs.ORIG_DICT }}
          asset_name: DE_morph_dict.txt
          asset_content_type: text/plain

      - name: Upload Whitelist Filtered Dictionary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.generate-files.outputs.WHITELIST_DICT }}
          asset_name: whitelist_dict.txt
          asset_content_type: text/plain

      - name: Upload Sensible Filtered Dictionary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.generate-files.outputs.FILTERED_DICT }}
          asset_name: DE_morph_dict_filtered.txt
          asset_content_type: text/plain
